### ISSUE TITLE
New daemon functionality has problems with seccomp

### ISSUE THREAD

**Issue by sre** [stoeckmann/xwallpaper#10]
Hi,

The new `--daemon` option crashes with SIGSYS when compiled with sandboxing support and without `DEBUG` defined. The exact crash position is main.c line 540 `daemon(0, 0)`, which tries to run the non-whitelisted `clone` syscall.

-- Sebastian

**Comment by stoeckmann** [comment]
Hi sre,

I have released version 0.4.1 which fixes the issue. Please let me know if everything works as expected and documented.


Tobias
