### ISSUE TITLE
Trying to install on Ubuntu

### ISSUE THREAD

**Issue by vladdoster** [stoeckmann/xwallpaper#14]
I love this utility. 

It seems that this package is available via apt, but I am having no luck.

https://launchpad.net/ubuntu/cosmic/+package/xwallpaper

Do I need to add a certain PPA? If so, do you know which?

**Comment by stoeckmann** [comment]
Hi vladdoster,

I've kept this issue open for some time so some Ubuntu user might reply. Seems like we ran out of luck here. I'll close this issue now because it is not something that can be fixed within xwallpaper but is more like a Ubuntu support request.

If you think otherwise, let me know.
