### ISSUE TITLE
30 bit color depth

### ISSUE THREAD

**Issue by abdalazizrashid** [stoeckmann/xwallpaper#15]
It fails to render 30 bit color depth.

**Comment by stoeckmann** [comment]
Hi, which input format did you use? I assume JPEG.

**Comment by stoeckmann** [comment]
Sounds like it will take a conversion to PIXMAN_a2r10g10b10 instead of always using PIXMAN_a8r8g8b8.

**Comment by stoeckmann** [comment]
Thank you for your report. I was able to get reproduce on a system configured to use 10 bpp.
I'll figure out a good way to resolve this issue, update the code and get back to you when it should finally work.

**Comment by stoeckmann** [comment]
Hi abdalazizrashid,

I have pushed changes which fixes output on my system with 16 bit and 30 bit root depth. Let me know if it works for you as well. If it does, I can release a new version.

**Comment by abdalazizrashid** [comment]
Hi, stockmann
I checked it with both 16 and 30 bit depth,  its rendering perfectly. So go ahead release and thanks
