### ISSUE TITLE
Can't actually change wallpaper on Ubuntu, jpg parse fail

### ISSUE THREAD

**Issue by BachoSeven** [stoeckmann/xwallpaper#17]
I built the last xwallpaper release on Ubuntu 18.04, and when I try `xwallpaper --zoom picture.jpg` I get  `failed to parse`(with --debug: `failed to parse XPM file`); with PNG I get either that, or a success which doesn't actually change my wallpaper. An example output for this last case:
```
loading /home/user/Pictures/image.png
output detected: eDP-1, 1920x1080+0+0
(randr) screen dimensions: 1920x1080+0+0
creating pixmap (1920x1080)
composing /home/user/Pictures/image.png for eDP-1 (area 1920x1080+0+0) (mode 6)
xcb image (1920x1080) to eDP-1 (1920x1080+0+0)
put image request parameters:
maximum request length allowed for server (32 bits): 4194303
maximum length for row data: 16777188
length of rows in image: 7680
maximum height to send: 2184
put image (1920x1080+0+0) to eDP-1 (1920x1080+0+0)
```

I noticed than while configuring the program I got this outputs, even though I think I have all the dependencies:
```
checking for JPEG... no
checking for SECCOMP... no
```

Also, with regards to #14 , there is a .deb available at https://launchpad.net/ubuntu/cosmic/amd64/xwallpaper/0.3.0-2ubuntu1 if you want, but it's an old version (0.3).

**Comment by stoeckmann** [comment]
Hi BachoSeven,

do you have jpeg header files installed, i.e. libjpeg-dev? If configure does not find JPEG, your system most likely lacks jpeg.h.

**Comment by stoeckmann** [comment]
Which window manager do you use? If you use a full desktop environment like Gnome or KDE, xwallpaper won't be able to change the wallpaper you see, because their default window managers handle the root window on their own.

**Comment by BachoSeven** [comment]
I see, thanks for clarifying. I guess disabling the wm's way of handling the root window would be harder than just using an alternative, since I indeed use Gnome; pywal will probably be my choice for now.
