### ISSUE TITLE
xwallpaper fails to follow symlinks

### ISSUE THREAD

**Issue by AtkLordOverAll** [stoeckmann/xwallpaper#18]
In the below, `~/.config/wallpaper` is a symlink to the JPEG file I have for my wallpaper. If I give it the actual file, it does work.

```
❯ xwallpaper --debug --center ~/.config/wallpaper
loading /home/atk/.config/wallpaper
failed to parse input as (RGB) JPEG
failed to parse XPM file
xwallpaper: failed to parse /home/atk/.config/wallpaper
```

Using Arch, xwallpaper 0.6.4, i3-gaps as my WM

Any other info wanted, please let me know :)

**Comment by stoeckmann** [comment]
Hi,

just created symlinks to a JPEG file (same directory, different directory, different filesystem). xwallpaper works as expected. Can you give me some more information about the symlink in question? "ls -l" output of symlink and destination file might help. Also, you might attach an "strace xwallpaper --center ~/.config/wallpaper" output.

**Comment by AtkLordOverAll** [comment]
Thanks for looking into this.

I'm a monumental idiot and be it the fault of myself or my wallpaper setting script I symlinked the folder, not the file.

Naturally xwallpaper can't set the background to be a folder, hence the above occurs. :disappointed: 

Sorry for wasting your time

**Comment by stoeckmann** [comment]
No worries. I prefer too many reports than missing a bug.
