### ISSUE TITLE
Not finding libjpeg on linux Mint 19

### ISSUE THREAD

**Issue by kandev** [stoeckmann/xwallpaper#19]
I hope I'm missing something, but still struggling with no success to compile xwallpaper with jpeg support.
I see that the libjpg is there:
```
$ ldconfig -p | grep libjpeg
        libjpeg.so.8 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libjpeg.so.8
        libjpeg.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libjpeg.so
```
But yet, when I do ./configure, that happends:
```
checking whether JPEG support is requested... auto
checking for JPEG... no
```
Any ideas how to proceed?

**Comment by stoeckmann** [comment]
The configure step also checks for header files. You are probably missing /usr/include/jpeglib.h (the exact path might be different). Linux Mint should have a libjpeg-dev package or something similar.

**Comment by stoeckmann** [comment]
Hi kandev,

I am closing this issue now because the issue has to be solved externally from xwallpaper (i.e. by installing additional software on your system). If you think otherwise, please let me know by re-opening the issue.
