### ISSUE TITLE
Regarding configure file not being able to find libjpeg for some users

### ISSUE THREAD

**Issue by brlipi** [stoeckmann/xwallpaper#25]
Hello.
Before I get into the subject, I must say I am not a Linux expert and I might not express myself in the clearest form due to technical ignorance.

I believe I have been able to find out why the configure file could not find the required library for JPEG support. It most probably is an issue exclusive to Ubuntu distributions which uses Ubuntu sourced packages. As per the following bug report: (https://bugs.launchpad.net/ubuntu/+source/libjpeg-turbo/+bug/1056566), the package did not even use to have a pkg-config file. Based on this I decided to look for said file and discovered that it exists but is missing its version and that is likely to be the crux of the problem: the configure script interprets the installed libjpeg as not being of at least version 1.5. Editing the file and adding a version greater than 1.5 solves the problem.
I am aware that this issue does not lie on your project, but with Ubuntu. I am already looking into how I can bring this issue to them in hopes of a fix. But I also believe that it might be of your interest to somehow, if even possible, adapt the configure.ac file so users of Ubuntu based distribution could enjoy xwallpaper fully. And if no possible changes can be done to the file, then maybe a small debugging paragraph on the README.md.

I apologize if raising an issue was not the best way to inform you of this problem.

**Comment by stoeckmann** [comment]
Hi @brlipi,

thanks for pointing this out. Maybe the libjpeg version requirement can be reduced in xwallpaper instead. I haven't checked anything older than versions which were available on my systems, so it is definitely possible that older versions will simply work. I was just not into claiming anything I haven't tested.

So, I will check the Ubuntu version and see what I can do.

Thanks!

**Comment by brlipi** [comment]
Thank you for deciding to look into this. I have uncovered some information that I believe might save some of your time on deciding if this Ubuntu problem could be remediated from the side of your program.

Yesterday I managed to find where to report a package related bug and discovered that the same problem had already been related before, in 2019 (https://bugs.launchpad.net/ubuntu/+source/libjpeg-turbo/+bug/1607696). In this thread, Sebastien Bacher (seb128) confirms the bug and says it was introduced when sed was added back in version 1.4.2 (http://launchpadlibrarian.net/241403193/libjpeg-turbo_1.4.2-0ubuntu2_1.4.2-0ubuntu3.diff.gz). Further down the thread the bug status went from "Confirmed" to "Fix commited". Then launchpad janitor posts the bug fix release, called "libjpeg-turbo (2.0.1-0ubuntu2) disco" (https://launchpad.net/ubuntu/+source/libjpeg-turbo/2.0.1-0ubuntu2.2). The problem is that I'm running Linux Mint 19 Tara, which is based on the LTS Ubuntu 18.04 Bionic Beaver. So the package manager aptitude works with the bionic version of package releases (in which the most recent version of libjpeg-turbo is 1.5.2) and this bug fix is only available for 19.04 Disco Dingo. And in the case of Linux Mint, only going from version 19 to 20 (Ulyana) will provide me with an OS based on a more recent version of Ubuntu, which is the Focal Fossa LTS. And to make matters more complicated, the libjpeg-turbo that must be installed through apt to have the .pc file, is actually **libjpeg-turbo8-dev**, regardless if source is xenial, bionic or focal. Maybe as a fix for me, personally I could look into backporting, which according to some comments on the internet, are discouraged as they can break other packages. But in regards to xwallpaper, maybe the best possible thing would be to instruct users of Ubuntu < 19.04 and Mint < 20 to manually install libjpeg-turbo8-dev, then check its version (with apt show libjpeg-turbo8-dev | grep Version), find the .pc file (maybe with sudo find / -name libjpeg.pc) and edit it with the editor of choice using sudo, since it is a readonly file, including the actual version of the installed library.

As you see, the more I dug into this problem, I realize the less it has to do with xwallpaper. So now I'm not sure

**Comment by stoeckmann** [comment]
Hi again @brlipi,

I would not recommend to modify files of your distribution. Checksums will turn invalid and this might lead to issues on later integrity checks.

Instead, I have added a simple header/library check. It is very basic, but in general the pkg-config approach is definitely the way to go. It is definitely not a fault of xwallpaper, and I would not adjust source code for this. But configure.ac is fine, since it tries to figure out how to compile itself on a system.

Let me know if it works for you.

**Comment by brlipi** [comment]
Hello.
Apparently, it did not work. I'm going to list everything I did up until the point where I ran "sudo make" and got an error:

Through apt, I removed libjpeg-turbo8-dev, which removed some other packages along with it.
Then I reinstalled the library together with what was removed with it.
I checked on /usr/share/x86_64-linux-gnu/pkgconfig for the libjpeg.pc file to see if it went back to its broken form. It did.
Then I went to my xwallpaper folder, pulled the changes from your repository, then opened configure.ac to check if it had your recent adjustment. It did.
So I ran ./autogen.sh, it gave the same output it did for me the other times I've ran this script.
Next, I ran ./configure. This was the output: https://pastebin.com/eusRr5UP. I personally do not see anything out of the norm here.
Lastly I ran sudo make. This was the console output: https://pastebin.com/jqvfFcXK. I honestly do not understand it.
And I must note I do have the file jpeglib.h, it is located in /usr/include.

If you have any problems accessing pastebin, let me know and I'll just post it here as a message.

**Comment by stoeckmann** [comment]
Ah yes, I see my mistake. JPEG_LIB is not used later on. When I analyzed the configure script, I erroneously found the pkg-config part which does all the relevant parts. Properly breaking my system led to the same issues. ;)

Let me know if it works now. And thank you for all your analysis and feedback.

**Comment by brlipi** [comment]
It worked! I even made sure it was thanks to your fix by removing the xwallpaper I already had installed with "make uninstall" (ran with sudo) and then ran the autogen, configure, make, make install sequence to make a fresh installation and it had no problems setting either .jpg, .jpeg, .png or .xpm. So I think the problem is completely fixed!

Thank you very much for you care and effort to fix an issue that does not stem from your program. I truly appreciate it.
If you want to ask for some more testing, feel free to do so. Otherwise I believe you can close this issue if you want, since everything is working fine here.

**Comment by stoeckmann** [comment]
Cool, thanks for letting me know about it. I'll close the issue then. Let me know if something else is not working though. :)
