### ISSUE TITLE
Include dependencies in readme.md

### ISSUE THREAD

**Issue by alt-art** [stoeckmann/xwallpaper#29]
Include `libxcb-util-dev` and `libxcb-image0-dev` as dependencies to build

**Comment by alt-art** [comment]
Other thing, i am tryng to use with `xwallpaper --zoom ./1.jpg`, but is not working.

**Comment by stoeckmann** [comment]
It really depends on your distribution which packages are a dependency. Yes it's true that you need the header files for xcb-util and xcb-image, but the exact package names differ, e.g. Arch Linux has no additional -dev packages. The header files are always installed.

To keep the readme file as clean as possible, I prefer to not add distribution-specific information.

Regarding your issue with calling xwallpaper, I would assume that you had no libjpeg header files installed during build time. You can check if xwallpaper has jpeg support by calling "ldd $(which xwallpaper)" and see if it is linked with libjpeg or libjpeg-turbo (also depends on jpeg libraries shipped by distributions). Also, running configure will show you if libjpeg is found.

The rational behind this is that it is perfectly fine to compile and use xwallpaper without jpeg support -- or without png or xpm support. Granted, an xwallpaper binary without any image file support makes no sense, it is an uncovered corner case of running configure which does not find any image libraries.

**Comment by alt-art** [comment]
This is idiotic, mememalism, if you want other people to use your program you should have build instructions for at least 3 linux distributions.

Put this in your fucking README.md:

Package to build on Debian distributions:
`sudo apt install libxcb-util-dev libxcb-image0-dev  libjpeg-turbo8-dev`

**Comment by stoeckmann** [comment]
First off I want to point out that I disagree with your choice of words. Closed issues are a good source of information in case people have similar problems, also I like to link to issues and replies so I do not have to write the same things over and over again. That being said, let's get back to the actual topic.

The documentation of xwallpaper should not be distribution-specific. It is a simple matter of "upstream" and "downstream", with downstream being distributors. They are experts in choosing projects to bundle and how they are supposed to work together. Also it would mean that, to keep current information, the readme would have to be updated for the latest fancy distribution or changes in their tools which also means version updates even if nothing changed in the program.

It's a poor argument to claim "others don't do it either" but I checked how xrandr and also feh or imlib handle this. They don't add these information to their readmes either. So it seems that my reasoning is not that off with reality.

Also it's a scalability issue. If every project explains how compilation dependencies are found, you have a lot of repeated text over and over all software projects.

Regarding your aspect of choosing 3 linux distributions: You can find already prepared packages/ports of xwallpaper for at least these systems:
- Arch Linux
- Debian
- Gentoo
- NixOS
- OpenBSD
- Ubuntu
- Void Linux

These packagers do a great job of providing an easy way of installing software to their users. Why should I write instructions how to compile software with their distribution when they already do it better and easier than I could? If you use a distribution or LTS version which has no xwallpaper and you really want to use it and make it easier for others to install it, I would suggest to create a port or package of it and submit it to your distributor.

Last but not least, the suggested line for readme is probably incomplete. You lack PNG support, XPM support which I can understand to skip, but also lack of seccomp, i.e. sandboxing. If someone compiles xwallpaper on a distribution which has a binary port, I think that person has very good reasons to choose support or lack of support of specific aspects. Where would you want to start and stop here? Also instruct how to install a compiler, choose between gcc and clang or jpeg and jpeg-turbo?

Therefore I simply cannot agree on adding these things to the readme. Even if it's "just about two lines."

**Comment by stoeckmann** [comment]
Since you have added the dependency and recommend to add this to the readme, I assume that xwallpaper works for you now. If nothing else is left to discuss and xwallpaper works at least technically for you, we can close this issue.

**Comment by alt-art** [comment]
I assume I've already switched to another program with support for two monitors, but it's just another issue for you to worry about.

**Comment by alt-art** [comment]
Since you already have package for xwallpaper, put this information in your readme.md

**Comment by stoeckmann** [comment]
For the record: xwallpaper supports multi monitor setups.

An example is explicitly stated in its manual page (see here: https://github.com/stoeckmann/xwallpaper/blob/master/xwallpaper.1#L144 ). The syntax is close to xrandr from which it is heavily inspired.

You can also read more about it in xwallpaper's wiki (see here: https://github.com/stoeckmann/xwallpaper/wiki/Advanced-Usage ).

Last  but not least the exact rational about xwallpaper's xrandr handling is explained in this issue: https://github.com/stoeckmann/xwallpaper/issues/20

**Comment by alt-art** [comment]
In my case, your program recognized my two monitors as one.

**Comment by stoeckmann** [comment]
I thought about it. And I think I know why this happened:

Multi monitor setup requires RandR, and the X C binding (xcb) have to supply that to X clients through libxcb-randr. Which means that the header files have to be installed. i.e. the -dev package of libxcb-randr.

High configurability is a blessing and a curse. In this case, it was definitely a curse. I know projects like weechat which expects people who compile the program from source to explicitly disable features through configure. I chose to stick with autoconf's "auto", i.e. enable if the library and header files are there, otherwise not.
