### ISSUE TITLE
Set wallpaper for a subset of outputs, leaving the others as is

### ISSUE THREAD

**Issue by mjkalyan** [stoeckmann/xwallpaper#32]
Currently (running v0.6.2 though I checked the releases and this doesn't seem to have changed) if you have multiple outputs you cannot set the wallpaper for only one of them without resetting the rest to black. Is it possible (or in the scope of the project) to set wallpapers for a subset of outputs and leave the other wallpapers as they currently are?

External workarounds exist but aren't particularly desirable. e.g. one could write some code to remember what output is set to what wallpaper (and with what settings) then append the unset outputs to the new `xwallpaper` call, updating with the new values. I hope there's a more elegant solution available internally.

**Comment by stoeckmann** [comment]
Hi @mjkalyan,

unfortunately there is no internal mechanism for this. And a real solution does not exist. See https://github.com/stoeckmann/xwallpaper/issues/20#issuecomment-611968446 for more details.

As stated there, nitrogen uses an atom-workaround for this and I know that there is a pull request in feh for this as well: https://github.com/derf/feh/pull/594

I am not sure if it is the proper way to go for xwallpaper though. In short: 0.6.2 definitely has no support for this.

**Comment by mjkalyan** [comment]
Ah, thank you! I read the thread in issue #20 and as I suspected it is technically more difficult than it seems. I like xwallpaper so I'll continue to use it with something similar to your symbolic link solution. In fact one of my use cases is also calling xwallpaper from sxiv, just like the fellow in #20.

Thanks again and I appreciate your work!
