### ISSUE TITLE
Request: support for webp images

### ISSUE THREAD

**Issue by afhp-2020** [stoeckmann/xwallpaper#40]
The man page explicitly states that this program mainly supports PNG images and optionally JPEG. A look at `configure` output indicates support for XPM as well.

As WEBP images are now popping up as a result of image searches, having this format supported as well would be nice, if at all possible.

**Comment by stoeckmann** [comment]
Hi @afhp-2020,

please see https://github.com/stoeckmann/xwallpaper/pull/31 for a possible solution and especially the reason why xwallpaper does not have webp support by now.

**Comment by afhp-2020** [comment]
Oh. Sorry, I scanned the issue list and managed to miss it, I wouldn't have posted this otherwise.

That said, I agree with your reasoning for not including it, converting the downloaded image is always an appropriate option.
