### ISSUE TITLE
Debug seems like it but I do not see the wallpaper

### ISSUE THREAD

**Issue by MichaelLieberman** [stoeckmann/xwallpaper#43]
I can't get xwallpaper to display the file. Instead it runs the initial file from settings/background.

Running Debian  Bullseye 
$ uname -r
5.19.0-0.deb11.2-amd64
Running on Nvidia GT730 2G 4HDMI

$xwallpaper --center --no-randr --tile moon.png 
$ xwallpaper --center --no-randr --tile moon.png --debug
loading moon.png
output detected: HDMI-1, 1920x1080+1920+0
output detected: HDMI-2, 1920x1080+3840+0
output detected: HDMI-3, 1920x1080+0+0
output detected: HDMI-4, 1920x1080+5760+0
(randr) screen dimensions: 7680x1080+0+0
creating pixmap (7680x1080)
tiling moon.png for HDMI-1 (area 1920x1080+0+0)
xcb image (1920x1080) to HDMI-1 (1920x1080+1920+0)
put image request parameters:
maximum request length allowed for server (32 bits): 4194303
maximum length for row data: 16777188
length of rows in image: 7680
maximum height to send: 2184
put image (1920x1080+0+0) to HDMI-1 (1920x1080+1920+0)
tiling moon.png for HDMI-2 (area 1920x1080+0+0)
xcb image (1920x1080) to HDMI-2 (1920x1080+3840+0)
put image request parameters:
maximum request length allowed for server (32 bits): 4194303
maximum length for row data: 16777188
length of rows in image: 7680
maximum height to send: 2184
put image (1920x1080+0+0) to HDMI-2 (1920x1080+3840+0)
tiling moon.png for HDMI-3 (area 1920x1080+0+0)
xcb image (1920x1080) to HDMI-3 (1920x1080+0+0)
put image request parameters:
maximum request length allowed for server (32 bits): 4194303
maximum length for row data: 16777188
length of rows in image: 7680
maximum height to send: 2184
put image (1920x1080+0+0) to HDMI-3 (1920x1080+0+0)
tiling moon.png for HDMI-4 (area 1920x1080+0+0)
xcb image (1920x1080) to HDMI-4 (1920x1080+5760+0)
put image request parameters:
maximum request length allowed for server (32 bits): 4194303
maximum length for row data: 16777188
length of rows in image: 7680
maximum height to send: 2184
put image (1920x1080+0+0) to HDMI-4 (1920x1080+5760+0)

**Comment by stoeckmann** [comment]
Hi,

since you mention that you've set a wallpaper in "settings/background", I assume that you use a desktop environment like Gnome, KDE, or XFCE. In these cases, the window manager does not use the X root image but has its own layer which is above the one set by xwallpaper. In short: xwallpaper works, but you don't see the result.

See https://github.com/stoeckmann/xwallpaper/issues/41 for more details and let me know which desktop environment you use.

**Comment by MichaelLieberman** [comment]
On Thu, 2022-11-17 at 13:03 -0800, Tobias Stoeckmann wrote:
> Hi,
> since you mention that you've set a wallpaper in
> "settings/background", I assume that you use a desktop environment
> like Gnome, KDE, or XFCE. In these cases, the window manager does not
> use the X root image but has its own layer which is above the one set
> by xwallpaper. In short: xwallpaper works, but you don't see the
> result.
> See #41 for more details and let me know which desktop environment
> you use.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
I am running Gnome-X.org, not Wayland or Plasma, though they are
installed and available. The 'settings application in the gnome-X.org
menu has a sub-setting called 'Background.'

Am I to understand that Gnome-X.org will not display the wallpaper? It
is either that or I don't see how the link you sent me is on point.

**Comment by stoeckmann** [comment]
I'll close this issue. If you have further questions or something's uncertain, feel free to reopen or create a new one!
