### ISSUE TITLE
Wallpaper is reset immediately by desktop environment

### ISSUE THREAD

**Issue by zxcv32** [stoeckmann/xwallpaper#44]
When setting wallpaper using the command `xwallpaper --zoom img.jpg` the wallpaper is immediately reset to the wallpaper that was set using the wallpaper settings of Kali.

Additional system details:
![image](https://user-images.githubusercontent.com/18421306/204794078-35ed04d9-ac73-475a-861f-f149b9568732.png)

Is there a fix or workaround that doesn't override the wallpaper set using xwallpaper by DE?
Alternatively, the wallpaper applicator may be disabled in Xfce but I haven't found a way to do it.

**Comment by stoeckmann** [comment]
Hi,

xwallpaper is not meant to be used in parallel with a desktop environment which handles the wallpaper by itself. If you have no chance to disable the DE from doing it, xwallpaper will eventually lose.

Besides, why do you want to use xwallpaper with a desktop environment, anyway?

**Comment by zxcv32** [comment]
huh.. apparently I understood that xwallpaper is used across distros to apply wallpapers. From your statement, it looks like it is for VM only.

**Comment by stoeckmann** [comment]
Yes, it is available across distributions. But it is supposed to be used with window managers like bspwm, cwm, dwm (just to name a few in alphabetical order) which do not modify the root window on their own.

Desktop environments normally do so. Most of them even put another window above the root window so xwallpaper looks like it doesn't work.
