### ISSUE TITLE
Regarding different images for different monitors

### ISSUE THREAD

**Issue by sandebert** [stoeckmann/xwallpaper#46]
I initially came here to ask pretty much the question in #32, which is about getting different images on different monitors - but failing because the other monitor gets black background instead. 

From that issue I found #20, leaving me sure I just couldn't get different images on different monitors using xwallpaper.

But then, in https://github.com/stoeckmann/xwallpaper/issues/20#issuecomment-612410727, I saw this code:
```
xwallpaper \
	--output "$monitor1" --zoom "$bgLoc/$monitor1" \
	--output "$monitor2" --zoom "$bgLoc/$monitor2"
```

Which made me try to set both monitors at the same time, and it worked just fine. The thing is that I found no information about being able to do it like this. The manpage (I'm on 0.6.5) states ”If multiple contradicting options were given, the last supplied option wins.” - which made me not even consider it a possibility to specify multiple outputs.

So, this issue is a mere suggestion to perhaps clarify this part of the manpage, and other documentation, so nobody else will miss that it's possible to get different images on all monitors - as long as it's done in a single command.

Thanks for a great utility!

**Comment by stoeckmann** [comment]
Sorry for getting back to you so late!

Isn't this covered in line https://github.com/stoeckmann/xwallpaper/blob/master/xwallpaper.1#L166 already?
