### ISSUE TITLE
JPEG XL support

### ISSUE THREAD

**Issue by avidseeker** [stoeckmann/xwallpaper#48]
Support .jxl image format.

See also: https://jpegxl.info

**Comment by stoeckmann** [comment]
Hi, even though in general it would be nice to support more formats, it isn't in scope of xwallpaper. The bare formats which are used within X software are jpeg, png, and xpm. So as long as the majority of wallpapers works with these, I'll keep it at that.

In general it would be nice to have gdk-pixbuf as a library for many fancy formats, but it's not part of X.

See https://github.com/stoeckmann/xwallpaper/pull/31 for more details.

**Comment by avidseeker** [comment]
Just as a note, this could also be done using imlib2 instead of gdk-pixbuf. Here's a simple wallpaper program based on it: https://github.com/ttzhou/setroot
