### ISSUE TITLE
Daemon encounters error on xrandr change

### ISSUE THREAD

**Issue by basil-conto** [stoeckmann/xwallpaper#52]
1. In my `~/.xsessionrc`, I start `xwallpaper --debug --daemon --zoom "${HOME}/.bg"` (where `~/.bg` is a symlink to a PNG file), and log into my X11 session.

   At this point, the wallpaper is set as expected, and `xwallpaper` is still running in the background.

2. I connect an external monitor, and call `xrandr` to turn my laptop's `eDP` output off and the appropriate `DisplayPort-<N>` output on.

   At this point, the `xwallpaper` daemon is dead, and the wallpaper does not adapt to the new geometry.

In the [attached `~/.xsession-errors`](https://github.com/user-attachments/files/17041943/default.xsession-errors.txt), the calls to `xrandr` are prefixed with `> `.

I would be grateful for any pointers on what's going wrong and how best to debug or work around it.

Thanks!

**Comment by stoeckmann** [comment]
Hi @basil-conto,

I can reproduce the problem thanks to your description and supplied xsession-errors file. I'll get back to you when I have a solution.

**Comment by stoeckmann** [comment]
Since you've also asked for a workaround: It seems that it's related to atoms. It works for me if `--no-atoms` is supplied. Can you check if this works for you?

The drawback is that neither pseudo-transparent windows would show the background and modifying just one wallpaper of a single monitor would set every other monitor to black.

**Comment by stoeckmann** [comment]
Getting closer ... A full workaround should be:

1. Run xwallpaper once without `--daemon`
2. Run xwallpaper with `--daemon`

I set atoms to be permanent, but somehow xwallpaper in daemon mode kills the atoms if they have to be replaced. Somehow, it ends up killing itself if there is no previous permanent atom of an xwallpaper instance that can be killed ... Weird, but at least a very good trace.

**Comment by stoeckmann** [comment]
I have pushed a commit. Can you try if it solves this issue?

**Comment by basil-conto** [comment]
> It works for me if `--no-atoms` is supplied. Can you check if this works for you?

If I run `xwallpaper` only once as a daemon with `--no-atoms` in `~/.xsessionrc`, then upon session login the wallpaper gets cleared (turns black).

> The drawback is that neither pseudo-transparent windows would show the background and modifying just one wallpaper of a single monitor would set every other monitor to black.

Not sure if my compositor interferes at all; I didn't check.

**Comment by basil-conto** [comment]
> I have pushed a commit. Can you try if it solves this issue?

Yes, I can no longer get the `xwallpaper` daemon to abort, even when I call `xwallpaper` only once (not twice as in the aforementioned workaround).

Thanks for the quick fix!

**Comment by stoeckmann** [comment]
That's great. Thank you for your detailed report and testing!

**Comment by stoeckmann** [comment]
> Not sure if my compositor interferes at all; I didn't check.

That sounds quite likely. If lack of atoms means that the background turns black means that you don't really see the X root window but the content of atoms. Since a compositor wants to add various effects, this is most likely the case.

I've tested with cwm, so in general it should work.

**Comment by stoeckmann** [comment]
I have released version 0.7.5 which fixes this issue. Thanks again for reporting!
